FROM python:3

RUN pip install mock nose tox wheel
RUN pip install colorlog>=2.7.0
RUN pip install coverage>=4.2
RUN pip install flask>=0.11.1
RUN pip install flask-restful>=0.3.5
RUN pip install flask-restful-swagger-2>=0.31
